#
# macro file for TestEm18.cc
#

#/control/cout/ignoreThreadsExcept 0

/control/verbose 2
/run/verbose 1
/tracking/verbose 0
#
#/testem/det/setMat G4_LEAD_OXIDE
#/testem/det/setMat G4_Pb
#/testem/det/setMat G4_Ag
/testem/det/setMat G4_Fe
#/testem/det/setMat G4_W
#/testem/det/setMat G4_Ba
#/testem/det/setMat G4_CONCRETE
#/testem/det/setMat G4_Zn
#/testem/det/setMat G4_Sn
#/testem/det/setMat G4_Zr
/testem/det/setSize 0.1 m
#
#/testem/phys/addPhysics standard
#
/run/setCut 0.01 mm
#
/run/initialize
/testem/trackSecondaries true
#
/gun/particle gamma
/gun/energy 100 GeV
#
/run/printProgress 1
/run/beamOn 100000