#
# macro file for TestEm18.cc
#
/control/cout/ignoreThreadsExcept 0
/control/verbose 2
/run/verbose 1
/tracking/verbose 0
#
#/testem/det/setMat G4_LEAD_OXIDE
#/testem/det/setMat G4_Pb
#/testem/det/setMat G4_Ag
/testem/det/setMat G4_Fe
#/testem/det/setMat G4_W
#/testem/det/setMat G4_Ba
#/testem/det/setMat G4_CONCRETE
#/testem/det/setMat G4_Zn
#/testem/det/setMat G4_Sn
#/testem/det/setMat G4_Zr
/testem/det/setSize 0.1 m
#
#/testem/phys/addPhysics standard
#
/run/setCut 0.01 mm
#
/run/initialize
/testem/trackSecondaries true
#
/gun/particle gamma
/gun/energy 100 GeV
#
/analysis/setFileName mu+
#
/analysis/h1/set  1 100 0    30 cm  #step size
/analysis/h1/set  2 100 0    2 GeV  #continuous Edeposited 
/analysis/h1/set  3 100 0 1000 GeV  #Etransfered by ionisation
/analysis/h1/set  4 100 0 1000 GeV  #Etransfered by brems
/analysis/h1/set  5 100 0 1000 GeV  #Etransfered by (e+,e-) prod
/analysis/h1/set  6 100 0 1000 GeV  #total Etransfered
/analysis/h1/set  7 100 0 1000 GeV  #total Elost
/analysis/h1/set  8 100 0 1000 GeV    #energy balance
/analysis/h1/set 11 100 0 1000 GeV  #gamma energy spectrum
/analysis/h1/set 12 100 0 1000 GeV  #e- energy spectrum
/analysis/h1/set 13 100 0 1000 GeV  #e+ energy spectrum
#
/run/printProgress 1
/run/beamOn 5000